name: Ruby Gem

on: [push]

jobs:
  release:
    name: Build + Publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Publish to RubyGems
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        OWNER: ${{ github.repository_owner }}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem install gem-release
        gem bump patch --tag --push --release
        gem build *.gemspec
        gem push *.gem
